### ISSUE TITLE
con.?文件在windows上无法被复制

### ISSUE THREAD

**Issue by fenglui** [tnfe/FFCreatorLite#1]
今天下载了项目压缩包，解压后发现缺失了con.js导致无法运行。
查了相关文档，发现原因如下：

不是所有的字母组合都可以用来命名文件夹，有些字母组合是不可以命名文件夹的，如con、aux、com1、com2、prn、con、nul、等。这些都是设备名，如果用这些字母组合，在win系统下会出现指定的设备名无效的错误提示。

建议：是否可以将con.js重新命名为其他名字。

**Comment by drawcall** [comment]
是的已经修复，非常感谢！
