### ISSUE TITLE
Add effect with infinite loop

### ISSUE THREAD

**Issue by armandoarmando** [tnfe/FFCreatorLite#10]
Hello everybody! I'm started to use the library and I love it! I need some help with the following:
I'm trying to add an effect (rotateIn) forever without success. Basically, I want to create a loop for this (from the beginning of the video until the end):

`imageFF.addEffect({
      type: 'rotateIn',
      time: 5,
});`

How can I do it? 

Many Thanks!
Armando

**Comment by drawcall** [comment]
Oh thanks. what effect do you want to achieve

**Comment by armandoarmando** [comment]
@drawcall rotateIn

**Comment by drawcall** [comment]
https://tnfe.github.io/FFCreator/#/guide/animate

```
image.addAnimate({
    from: { rotate: 0 },
    to: { ratate:  3.14159* n},
    time : n
});
```

**Comment by armandoarmando** [comment]
FFCreator start
../ffcreatorlite/node_modules/ffcreatorlite/lib/animate/animations.js:194
      if (filter.type == 'array') {
                 ^

TypeError: Cannot read property 'type' of null

**Comment by drawcall** [comment]
please use FFCreator https://github.com/tnfe/FFCreator

**Comment by armandoarmando** [comment]
I wanted to use FFCreatorLite bc is faster. In any case, thank you very much @drawcall
