### ISSUE TITLE
 Unable to find a suitable output format for \'sksnxgdgurdlnp5t\'\nsksnxgdgurdlnp5t: Invalid argument\n',

### ISSUE THREAD

**Issue by luohuan** [tnfe/FFCreatorLite#3]
`const {FFCreatorCenter, FFScene, FFImage, FFText, FFCreator} = require('ffcreatorlite');
const colors = require('colors')

const creator = new FFCreator({
  width: 600,
  height: 400,
  log: true,
});

let bg1 = 'https://qncdn.mopic.mozigu.net/f/nutth04rv4ukf19bcno/2-3b.jpg'

const scene1 = new FFScene();
const scene2 = new FFScene();
scene1.setBgColor('#ff0000');
scene2.setBgColor('#b33771');

// scene1
const fbg = new FFImage({path: bg1});
scene1.addChild(fbg);

// const fimg1 = new FFImage({path: img1, x: 300, y: 60});
// fimg1.addEffect('moveInRight', 1.5, 1.2);
// scene1.addChild(fimg1);

// const text = new FFText({text: '这是第一屏', font, x: 100, y: 100});
// text.setColor('#ffffff');
// text.setBackgroundColor('#000000');
// text.addEffect('fadeIn', 1, 1);
// scene1.addChild(text);

scene1.setDuration(8);
creator.addChild(scene1);

// // scene2
// const fbg2 = new FFImage({path: bg2});
// scene2.addChild(fbg2);
// // logo
// const flogo = new FFImage({path: logo, x: 100, y: 100});
// flogo.addEffect('moveInUpBack', 1.2, 0.3);
// scene2.addChild(flogo);

// scene2.setDuration(4);
// creator.addChild(scene2);

creator.start();

creator.on('progress', e => {
  console.log(colors.yellow(`FFCreatorLite progress: ${(e.percent * 100) >> 0}%`));
});

creator.on('complete', e => {
  console.log(
    colors.magenta(`FFCreatorLite completed: \n USEAGE: ${e.useage} \n PATH: ${e.output} `),
  );
});`

### hello i want to run the simplest example and this error come out , i can;t find a solution please help me

Error [ERR_UNHANDLED_ERROR]: Unhandled error. ({ type: 'error',
  error:
   'Error: ffmpeg exited with code 1: sksnxgdgurdlnp5t: Invalid argument\n \n stdout:  \n stderr: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x6b4e0c0] Auto-inserting h264_mp4toannexb bitstream filter\n    Last message repeated 1 times\nInput #0, concat, from \'/tmp/27c9498c906eb9db09e92312a7cdd152/coyuh5fyekqzmfkx.txt\':\n  Duration: N/A, start: 0.000000, bitrate: 53 kb/s\n    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 600x400 [SAR 1:1 DAR 3:2], 20 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc\n    Metadata:\n      handler_name    : VideoHandler\n    Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 700x700 [SAR 1:1 DAR 1:1], 33 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc\n    Metadata:\n      handler_name    : VideoHandler\n[NULL @ 0x6c21440] Unable to find a suitable output format for \'sksnxgdgurdlnp5t\'\nsksnxgdgurdlnp5t: Invalid argument\n',
  pos: 'Synthesis' })

### **then i run the example/images  this error come out**

ffmpeg -f concat -safe 0 -i /home/harvey/test_ff/examples/cache/qhgrfv1beiolw5di.txt -stream_loop -1 -i /home/harvey/test_ff/examples/assets/audio/01.wav -y -hide_banner -map_metadata -1 -map_chapters -1 -c copy -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p -r 24 -c:a aac -shortest 03pmos6o7sbye4rl
{ type: 'error',
  error:
   'Error: ffmpeg exited with code 1: 03pmos6o7sbye4rl: Invalid argument\n \n stdout:  \n stderr: [mov,mp4,m4a,3gp,3g2,mj2 @ 0x6855240] Auto-inserting h264_mp4toannexb bitstream filter\n    Last message repeated 1 times\nInput #0, concat, from \'/home/harvey/test_ff/examples/cache/qhgrfv1beiolw5di.txt\':\n  Duration: N/A, start: 0.000000, bitrate: 365 kb/s\n    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 600x400 [SAR 1:1 DAR 3:2], 309 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc\n    Metadata:\n      handler_name    : VideoHandler\n    Stream #0:1(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p, 600x400, 56 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc\n    Metadata:\n      handler_name    : VideoHandler\nGuessed Channel Layout for Input Stream #1.0 : stereo\nInput #1, wav, from \'/home/harvey/test_ff/examples/assets/audio/01.wav\':\n  Metadata:\n    encoder         : FL Studio 9\n  Duration: 00:00:17.45, bitrate: 1411 kb/s\n    Stream #1:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 44100 Hz, stereo, s16, 1411 kb/s\n[NULL @ 0x69d4480] Unable to find a suitable output format for \'03pmos6o7sbye4rl\'\n03pmos6o7sbye4rl: Invalid argument\n',
  pos: 'Synthesis' }

**Comment by drawcall** [comment]
Please specify the output directory, I made it successfully with your code

```
const outputDir = path.join(__dirname, './output/');
const cacheDir = path.join(__dirname, './cache/');

const createImageAnimation = () => {
  const creator = new FFCreator({
    width: 600,
    height: 400,
    log: true,
    cacheDir,
    outputDir,
  });
```


https://user-images.githubusercontent.com/3407208/103276049-8367b780-4a00-11eb-9b57-e661c5f691cb.mp4

**Comment by luohuan** [comment]
I also run you example/image.js  which file specify the output directory，bu still get the same error

**Comment by drawcall** [comment]
Please download version 1.4.9 to try
