### ISSUE TITLE
lite版都支持那些动画呢?在Animate.css上复制下来的动画都没效果

### ISSUE THREAD

**Issue by 404isNotFound** [tnfe/FFCreatorLite#6]
` const fvideo1 = new FFVideo({path: video1 });
  fvideo1.setScale(0.6);
  fvideo1.setWH(width, height);
  scene2.addChild(fvideo1);
  // 文字
  const text2 = new FFText({text: '视频1', font, x: 140, y: 100, fontSize: 42});
  text2.setColor('#ffffff');
  text2.addEffect('fadeInRight', 2, 1);
  scene2.addChild(text2);
  creator.addChild(scene2);
  // 视频2
  const fvideo2 = new FFVideo({path: video2 });
  fvideo1.setScale(0.6);
  // fvideo2.setWH(width, height);
  scene3.addChild(fvideo2);
  // 文字
  const text3 = new FFText({text: '视频2', font, x: 140, y: 100, fontSize: 42});
  text3.setColor('#ffffff');
  text3.addEffect('bounceInRight', 2, 1);
  scene3.addChild(text3);
  creator.addChild(scene3);
  // 视频3
  const fvideo3 = new FFVideo({path: video3 });
  fvideo1.setScale(0.6);
  fvideo3.setWH(width, height);
  scene4.addChild(fvideo3);
  // 文字
  const text4 = new FFText({text: '视频3', font, x: 140, y: 100, fontSize: 42});
  text4.setColor('#ffffff');
  text4.addEffect('fadeInTopRight', 2, 1);
  scene4.addChild(text4);
  creator.addChild(scene4);`

**Comment by drawcall** [comment]
You can view[here](https://github.com/tnfe/FFCreatorLite/blob/master/lib/animate/effects.js), welcome to submit PR

**Comment by 404isNotFound** [comment]
Thank you very much.
