### ISSUE TITLE
已经为FFtext传入了字体文件,但出现中文乱码

### ISSUE THREAD

**Issue by 404isNotFound** [tnfe/FFCreatorLite#7]
我按照文档为字体传入了字体文件,但是结果是出现了中文乱码
`  
  const fimg1= new FFImage({ path: img1, y: 300 });
  fimg1.addEffect('zoomIn', 1,1);
  scene1.addChild(fimg1);

const font = path.join(__dirname, '../static/font/scsf.ttf');
 const text1 = new FFText({text: 'FFCreatorLite动画效果', font, x: 140, y: 100, fontSize: 42});
  text1.setColor('#ffffff');
  text1.setBorder(5, '#000000');
  text1.addEffect('moveInRight', 2, 1);
  scene1.addChild(text1);`
这是合成的视频:
https://user-images.githubusercontent.com/52105855/104282024-5ed40b00-54e9-11eb-89df-9c54720132ff.mp4

**Comment by 404isNotFound** [comment]
我运行demo没有出现这个问题,,我不明白我哪里写错了;

**Comment by 404isNotFound** [comment]
这是我的完整代码:
`const path = require('path');
const {FFCreatorCenter, FFScene, FFVideo, FFText, FFCreator, FFImage} = require('ffcreatorlite');
const outputDir = path.join(__dirname, '../output/');
const cacheDir = path.join(__dirname, './cache/');
const width = 576;
const height = 1024;
const createFFTaskTemplate = () => {

  const img1 = path.join(__dirname, '../static/image/hj/01.jpeg');
  const img2 = path.join(__dirname, '../static/image/hj/02.jpeg');
  const img3 = path.join(__dirname, '../static/image/hj/03.jpeg');
  const img4 = path.join(__dirname, '../static/image/hj/04.jpeg');
  const img5 = path.join(__dirname, '../static/image/hj/05.jpeg');

  const font = path.join(__dirname, '../static/font/scsf.ttf');
  const audio = path.join(__dirname, '../static/audio/music1.mp3');
  const video1 = path.join(__dirname, '../static/video/1.flv');
  const video2 = path.join(__dirname, '../static/video/1.flv');
  const video3 = path.join(__dirname, '../static/video/1.flv');
  // create creator instance
  const creator = new FFCreator({
    cacheDir,
    outputDir,
    width,
    height,
    log: true,
    audio
  });


  // 场景
  const scene1 = new FFScene();
  const scene2 = new FFScene();
  const scene3 = new FFScene();
  const scene4 = new FFScene();
  scene1.setBgColor('#FC6493');
  scene2.setBgColor('#FC6493');
  scene3.setBgColor('#FC6493');
  scene4.setBgColor('#FC6493');
  // 场景一  图片
  const fimg1 = new FFImage({path: img1, y: 300});
  fimg1.addEffect('zoomIn', 1, 1);
  scene1.addChild(fimg1);

  const text1 = new FFText({fontSize: 42});
  text1.setText('FFCreatorLite图片测试');
  text1.setColor('#ffc310');
  text1.setXY(140, 100);
  text1.setFont(font);
  text1.addEffect('moveInUp', 1, 2);
  scene1.addChild(text1);

  const fimg2 = new FFImage({path: img2, y: 300});
  fimg2.addEffect('zoomIn', 1, 4);
  scene1.addChild(fimg2);

  const fimg3 = new FFImage({path: img3, y: 300});
  fimg3.addEffect('zoomIn', 1, 6);
  scene1.addChild(fimg3);

  const fimg4 = new FFImage({path: img4, y: 300});
  fimg4.addEffect('zoomIn', 1, 8);
  scene1.addChild(fimg4);

  const fimg5 = new FFImage({path: img5, y: 300});
  fimg5.addEffect('zoomIn', 1, 10);
  scene1.addChild(fimg5);
  creator.addChild(scene1);
  

  creator.start();
  creator.openLog();
  return creator
};

module.exports = (param) => FFCreatorCenter.addTask(() => createFFTaskTemplate(param));





`

**Comment by 404isNotFound** [comment]
可以帮助一下我吗,这个问题至今我还未解决

**Comment by 404isNotFound** [comment]
@drawcall

**Comment by 404isNotFound** [comment]
@drawcall

**Comment by drawcall** [comment]
Oh, I'm sorry I'm a bit busy and can't reply in time. I can’t repeat your error, so I can’t find out what's wrong for now?

It may be that the system is not compatible with the font or the font file does not use utf-8, you can try another font.

**Comment by drawcall** [comment]
Because the principle of `ffcreatelite` is to splice ffmpeg commands, so you can google _ffmpeg 中文乱码_

**Comment by 404isNotFound** [comment]
我用你提供的demo是没有任何问题的,但不知道我自己的项目为什么会出现这种情况,我也试过重新下载字体文件,也没用,我正在尝试重新用你的demo来构建我的项目,希望有用..

**Comment by 404isNotFound** [comment]
另外我还发现一个问题,期望你能给我解答,我的期望是在一个背景为黑色的场景里边出现一个居中的文字提示,因此我有了下边的代码:
1:  `const livePreViewScene = ({textConfig}) => {
  const preViewScene = new FFScene();
  preViewScene.setBgColor('#000000');
  const text = createText(textConfig);
  preViewScene.addChild(text);
  preViewScene.setDuration(5);
  return preViewScene
};`
代码看起来是没什么问题的,但是我运行的时候出现报错: `ffmpeg exited with code 1: Invalid input file index: 0 ` ,我尝试去搜索却找不到对我有帮助的答案,反复试错无果后我尝试在这个场景里加入了别的元素FFVideo,下边是我修改后的代码:
2:  `const livePreViewScene = ({textConfig}) => {
  const preViewScene = new FFScene();
  preViewScene.setBgColor('#000000');
  // ===新增=== ↓
  const fvideo = new FFVideo({path: path.join(__dirname,'../static/video/1.mp4')});
  preViewScene.addChild(fvideo);
// ===新增=== ↑
  const text = createText(textConfig);
  preViewScene.addChild(text);
  preViewScene.setDuration(5);
  return preViewScene
};`
这段代码神奇的可以运行, 为此我陷入了困惑,是不是一个场景里不可以只添加字体元素? 为此我翻看文档,并没有相关解释,希望你可以给我解释下.

**Comment by 404isNotFound** [comment]
上述序列为1的代码 在运行报错时我查看源码发现 在运行到 源码 processor.js 文件第25行 (下方为源码代码):
`function runFfprobe(command) {
  const inputProbeIndex = 0;
// 25 行 ↓
  if (command._inputs[inputProbeIndex].isStream) {
    // Don't probe input streams as this will consume them
    return;
  }
  command.ffprobe(inputProbeIndex, function(err, data) {
    command._ffprobeData = data;
  });
}` 
的时候 ` if (command._inputs[inputProbeIndex].isStream)` 这个条件 始终是 false , 我并不知道发生了什么, 希望这个可以帮助到你你

**Comment by 404isNotFound** [comment]
再次感谢你,在百忙之中回答我的问题 @drawcall

**Comment by drawcall** [comment]
Oh yes, in this case I recommend you to add a background image. I think ffmpeg was not born for making animation. ffcreatorlite is just an animation synthesis that cleverly uses some of its functions.

**Comment by 404isNotFound** [comment]
非常感谢你为我解答,同时我也期待你的新作品上线.

**Comment by 404isNotFound** [comment]
` const font1 = path.join(__dirname, './assets/font/ysst.ttf');
  const font2 = path.join(__dirname, './assets/font/jdnt.ttf');`
我按照demo这种方式为我的视频中的文字更换字体,是行不通的;
Google给出的答案是要对路径进行转义:
无效的路径: `C:\Users\cell\Desktop\GenerateVideo\static\font\jdnt.ttf`
有效的路径: `C\:/Users/cell/Desktop/GenerateVideo/static/font/klt.ttf `
"\"要更换为"/" 并且 ":"前面要加转义;
希望迭代新版本的时候可以在文档中标注一下,感谢 @drawcall

**Comment by drawcall** [comment]
> ` const font1 = path.join(__dirname, './assets/font/ysst.ttf'); const font2 = path.join(__dirname, './assets/font/jdnt.ttf');`
> 我按照demo这种方式为我的视频中的文字更换字体,是行不通的;
> Google给出的答案是要对路径进行转义:
> 无效的路径: `C:\Users\cell\Desktop\GenerateVideo\static\font\jdnt.ttf`
> 有效的路径: `C\:/Users/cell/Desktop/GenerateVideo/static/font/klt.ttf `
> ""要更换为"/" 并且 ":"前面要加转义;
> 希望迭代新版本的时候可以在文档中标注一下,感谢 @drawcall

thanks
