### ISSUE TITLE
代码在window环境上运行正常,放到服务器就会报错,但是文档提供的demo在服务器可以运行

### ISSUE THREAD

**Issue by 404isNotFound** [tnfe/FFCreatorLite#9]
这是window系统下FFmpeg版本: 
![window](https://user-images.githubusercontent.com/52105855/108679391-6b577480-7527-11eb-9728-af8eecaf364a.png)
这是liunx系统下FFmpeg版本: 
![cent7](https://user-images.githubusercontent.com/52105855/108679423-78746380-7527-11eb-8b90-529ee82c1b1f.png)
经常会报这个错误 `error: Error: ffmpeg exited with code 1: Error initializing complex filters`

**Comment by 404isNotFound** [comment]
这是项目部分代码: `/**
 *  文字
 * @author superpositives@163.com
 * @param TEXT_CONFIG
 * @returns FFText 实例
 * @date 2021/1/13 11:11
 */
const createText = ({text, color, effect, y, fontsize, bds, bdc, effectTime, effectDelay}) => {
    const textObj = new FFText({fontSize: fontsize});
    textObj.setText(text);
    textObj.setColor(color);
    textObj.setBorder(bds, bdc);
    // 文字水平垂直居中
    let W = WIDTH / 2;
    let centerX = W - ((text.length * fontsize) / 2);
    let centerY = y - fontsize;
    textObj.setXY(centerX, centerY);
    textObj.setFont(font);
    textObj.addEffect(effect, effectTime, effectDelay);
    return textObj
};

/**
 *  相册 + 文字
 * @author superpositives@163.com
 * @param  {Array} imgPath 限制10张之内
 * @param  {TEXT_CONFIG} textConfig 文字
 * @param  {string} sceneBgColor 场景背景色
 * @param  {number} setTime 间隔秒
 * @returns  FFScene 实例
 * @date 2021/1/13 10:31:13
 */
const createAlbum = ({imgPath, setTime, textConfig, sceneBgColor = SCENE_BGCOLOR}) => {
    const imgScene = new FFScene();
    imgScene.setBgColor(sceneBgColor);
    imgScene.setDuration(6);
    const interval = [0].concat([2, 3, 4, 5, 6, 7, 8, 9, 10].map(item => item * setTime));
    for (let i = 0, len = imgPath.length; i < len; i++) {
        if (i !== 0) {
            const fimg1 = new FFImage({path: imgPath[i], y: 300});
            fimg1.addEffect('zoomIn', 1, interval[i]);
            imgScene.addChild(fimg1);
        } else {
            const fimg1 = new FFImage({path: imgPath[i], y: 300});
            fimg1.addEffect('zoomIn', 1, interval[i]);
            imgScene.addChild(fimg1);
            // // 添加文字
            const text = createText(textConfig);
            imgScene.addChild(text);
        }
    }
    return imgScene
};

/**
 *  视频 + 文字
 * @author superpositives@163.com
 * @param {VIDEO_CONFIG}  videConfig
 * @param {TEXT_CONFIG}  textConfig
 * @returns  FFScene 实例
 * @date 2021/1/13 10:36:35
 */
const createVideo = ({videConfig, textConfig}) => {
    const {path : videoPath, w, h, scale, duration} = videConfig;
    const videoScene = new FFScene();
    const fvideo = new FFVideo({path: videoPath});
    fvideo.setScale(scale);
    fvideo.setWH(w, h);
    // fvideo.setAudio(false);
    videoScene.addChild(fvideo);
    // 文字
    const text = createText(textConfig);
    videoScene.addChild(text);
    videoScene.setDuration(duration);
    return videoScene
};
/**
 * 预览视频 直播画面
 * @author superpositives@163.com
 * @returns  FFScene 实例
 * @date 2021/1/15 14:47:24
 */
const livePreViewScene = ({textConfig}) => {
    const preViewScene = new FFScene();
    preViewScene.setBgColor('#000000');
    const img = new FFImage({path: path.join(__dirname, '../static/image/black.jpg')});
    img.setWH(WIDTH, HEIGHT);
    preViewScene.addChild(img);
    const text = createText(textConfig);
    preViewScene.addChild(text);
    preViewScene.setDuration(3);
    return preViewScene
};


/**
 *  随机数
 * @author superpositives@163.com
 * @param {number} min 随机最小值
 * @param {number} max 随机最大值
 * @returns {number} 最小值 与 最大值 之间的随机数  [不包含最大值]
 * @date 2021/1/15 14:44:42
 */
const RandomNum = function (min, max) {
    return Math.floor(Math.random() * (max - min) + min)
};

/**
 *  乱序
 * @author superpositives@163.com
 * @param  {Array} array
 * @returns  {Array}
 * @date 2021/1/18 15:40:47
 */
const sortHandle = (array) => {
    const randomTem = [];
    while (!(randomTem.length === 3)) {
        let random = RandomNum(0, 3);
        if (!(randomTem.some(item => item.pathType === array[random].pathType))) {
            randomTem.push(array[random]);
        }
    }
    return randomTem
};

// 全局变量
let sort = [];
let imgPosition = null;
let imgType = null;
let videoType = null;
// 视频模板    { cp:path:[]} ,md:{ path:[]} ,hj:{ path:[]},bgm:{ path:[]} ,zb:{ path:[]}   }
const createFFTaskTemplate = ({cp, md, hj, bgm, zb, roomText, fmPath, taskId}) => {
    // 初始化全局变量
    sort = [];
    imgPosition = null;
    imgType = null;
    videoType = null;
    // 分割封面url
    let splits = fmPath.split('/');
    let fmName = splits[splits.length - 1];
    let fmName2 = fmName.split('.')[0];
    logger.info(`开始合成视频,当前任务id: ${taskId}`);
    const creator = new FFCreator({
        cacheDir,
        outputDir,
        width: WIDTH,
        height: HEIGHT,
        log: false,
        debug: true,
        audioLoop: true,
        audio: bgm.path[0],
        // audio:  path.join(__dirname, '../static/image/1.mp3'),
        // output: `${taskId}_${new Date().getTime()}`
    });
    // 相册
    const addChildAlbumHandle = ({path, text}) => {
        creator.addChild(createAlbum({
            imgPath: path,
            setTime: 1,
            textConfig: Object.assign(deep(TEXT_CONFIG), {
                text: text,
                effectDelay: 0
            })
        }));
    };
    // 视频
    const addChildVideoHandle = ({path, text}) => {
        creator.addChild(createVideo({
            videConfig: Object.assign(deep(VIDEO_CONFIG), {
                path: path,
                duration: 5,
                scale: 1
            }),
            textConfig: Object.assign(deep(TEXT_CONFIG), {
                text: text
            })
        }));
    };
    // 乱序
    const randomTem = sortHandle([cp, md, hj]);
    // 遍历
    for (const key of randomTem) {
        sort.push(key.pathType);
        if (key.type === 'img') {
              key.path.forEach((item, index) => {
                let pathSplit = item.split('/');
                let imgName = pathSplit[pathSplit.length - 1];
                let imgName2 = imgName.split('.')[0];
                if (imgName2 === fmName2) {
                  imgPosition = index + 1;
                  imgType = key.pathType;
                }
              });
            // 调用相册
            addChildAlbumHandle({
                path: key.path,
                text: key.text
            })
        } else {
            // 调用视频
            addChildVideoHandle({
                path: key.path[0],
                text: key.text
            })
        }
    }
    // 判断合成视频类型
    if (zb.path[0]) {
      videoType = 'code';
      logger.info(`当前视频为扫码视频,当前任务id: ${taskId}`);
      addChildVideoHandle({path: zb.path[0], text: roomText});
    } else {
      videoType = 'preview';
      logger.info(`当前视频为预览视频,当前任务id: ${taskId}`);
      creator.addChild(livePreViewScene({
        textConfig: Object.assign(deep(TEXT_CONFIG), {
          text: '该画面为直播画面',
          color: '#ffffff',
          y: HEIGHT / 2,
          bdc: '#ffffff',
          effectDelay: 1,
          bds: 1
        })
      }));
    }
    creator.openLog();
    creator.start();
    return creator
};

module.exports = (param) => {
    let id = FFCreatorCenter.addTask(() => createFFTaskTemplate(param));
    return {
        id,
        sort,
        imgPosition,
        imgType,
        videoType
    }
};`

**Comment by 404isNotFound** [comment]
@drawcall  非常急迫的请求你的帮助

**Comment by 404isNotFound** [comment]
这是日志信息: `当前任务id: 47,合成视频参数====>{"fmPath":"http://pic.aikeai.group/1612513588235.png","roomText":"卍般若巴嘛空卍","taskId":47,"cp":{"path":["/pv/ffproject/static/47/cp/1612513505425.mp4"],"text":"卍世尊地藏卍","pathType":"cp","type":"video"},"md":{"path":["/pv/ffproject/static/47/md/1612513588235.png"],"text":"卍大威天龙卍","pathType":"md","type":"img"},"hj":{"path":["/pv/ffproject/static/47/hj/1612513548853.mp4"],"text":"卍般若诸佛卍","pathType":"hj","type":"video"},"bgm":{"path":["/pv/ffproject/static/47/bgm/1612420583035.mpeg"],"pathType":"bgm"},"zb":{"path":[],"pathType":"zb"}}
[2021-02-22T16:20:00.634] [INFO] liveMeeting - 开始合成视频,当前任务id: 47
[2021-02-22T16:20:00.637] [INFO] liveMeeting - 当前视频为预览视频,当前任务id: 47
[2021-02-22T16:20:00.638] [INFO] liveMeeting - 模板id:05bfax3l6wkhwqfe--任务id:47,模板排序顺序:["md","hj","cp"],封面图片所在位置:1,封面所在类型:md,封面出现时间:1.5s,当前视频类型:preview
single: ffmpeg -i /pv/ffproject/static/47/hj/1612513548853.mp4 -y -filter_complex color=c=#000000:d=5:size=576*1024[background3-0];[background3-0][0:v]overlay=x=0:y=0[video1-1];[video1-1]drawtext=bordercolor=#000000:borderw=3:fontcolor=#FFFC00:fontfile=/pv/ffproject/static/font/klt.ttf:fontsize=60:text=卍般若诸佛卍:alpha='if(between(t,2,3),0+1*(t-2)/1,1)':x='if(between(t,2,3),108+0*(t-2)/1-0*pow((t-2)/1,2),108)':y='if(between(t,2,3),-30+200*(t-2)/1-100*pow((t-2)/1,2),70)':enable='between(t,2,99999)'[text2-1] -map [text2-1] -r 24 -t 5 -map 0 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p /pv/ffproject/Template/cache/quitqtfnm6jto46n/scene2.mp4
single: ffmpeg -loop 1 -i /pv/ffproject/static/47/md/1612513588235.png -y -filter_complex color=c=#000000:d=6:size=576*1024[background2-0];[0:v]format=yuva420p,pad=2*iw:2*ih:(ow-iw)/2:(oh-ih)/2:black@0,scale=4000x4000,zoompan=z='if(between(on,-1,24),1+1*on/24,2)':d='24':x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s='600*400':fps='24'[image1-1];[image1-1]fade=type=in:st=0:d=1:color=black:alpha=1[image1-2];[background2-0][image1-2]overlay=x=0:y=300[image1-3];[image1-3]drawtext=bordercolor=#000000:borderw=3:fontcolor=#FFFC00:fontfile=/pv/ffproject/static/font/klt.ttf:fontsize=60:text=卍大威天龙卍:alpha='if(between(t,0,1),0+1*t/1,1)':x='if(between(t,0,1),108+0*t/1-0*pow(t/1,2),108)':y='if(between(t,0,1),-30+200*t/1-100*pow(t/1,2),70)':enable='between(t,0,99999)'[text1-1] -map [text1-1] -r 24 -t 6 -map 0 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p /pv/ffproject/Template/cache/gbnyyx5p7nrz942y/scene1.mp4
[2021-02-22T16:20:00.790] [INFO] liveMeeting - 当前任务id: 47,制作失败,耗时0,当前任务id: 47,报错信息:
[2021-02-22T16:20:00.790] [INFO] liveMeeting - {
  id: '05bfax3l6wkhwqfe',
  error: {
    type: 'error',
    error: Error: ffmpeg exited with code 1: /pv/ffproject/static/47/hj/1612513548853.mp4: Invalid data found when processing input
    
        at ChildProcess.<anonymous> (/pv/ffproject/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
        at ChildProcess.emit (events.js:210:5)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12),
    target: FFScene {
      _events: [Object],
      _eventsCount: 4,
      _maxListeners: undefined,
      conf: [Object],
      type: 'scene',
      parent: [FFCreator],
      id: 'scene2',
      children: [Array],
      filters: [Array],
      vLength: 1,
      hasInput: false,
      context: [FFContext],
      command: [FfmpegCommand],
      percent: 0,
      duration: 5,
      directory: '/pv/ffproject/Template/cache/quitqtfnm6jto46n',
      pathId: 'quitqtfnm6jto46n',
      background: [FFBackGround],
      filepath: '/pv/ffproject/Template/cache/quitqtfnm6jto46n/scene2.mp4'
    }
  },
  eventName: 'single-error'
}

[2021-02-22T16:20:00.810] [INFO] liveMeeting - 当前任务id: 47,制作失败,耗时0,当前任务id: 47,报错信息:
[2021-02-22T16:20:00.811] [INFO] liveMeeting - {
  id: '05bfax3l6wkhwqfe',
  error: {
    type: 'error',
    error: Error: ffmpeg exited with code 1: Error initializing complex filters.
    Option not found
    
        at ChildProcess.<anonymous> (/pv/ffproject/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
        at ChildProcess.emit (events.js:210:5)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12),
    target: FFScene {
      _events: [Object],
      _eventsCount: 4,
      _maxListeners: undefined,
      conf: [Object],
      type: 'scene',
      parent: [FFCreator],
      id: 'scene1',
      children: [Array],
      filters: [Array],
      vLength: 1,
      hasInput: false,
      context: [FFContext],
      command: [FfmpegCommand],
      percent: 0,
      duration: 6,
      directory: '/pv/ffproject/Template/cache/gbnyyx5p7nrz942y',
      pathId: 'gbnyyx5p7nrz942y',
      background: [FFBackGround],
      filepath: '/pv/ffproject/Template/cache/gbnyyx5p7nrz942y/scene1.mp4'
    }
  },
  eventName: 'single-error'
}
`

**Comment by drawcall** [comment]
Are there special characters in the text. Sorry i'm busy

**Comment by 404isNotFound** [comment]
> 文字中是否有特殊字符。不好意思，我在忙

卍 符号去调后仍然报错, 而且加上这个符号在window环境下可以生成,感谢百忙之中回答我的问题,还请有空帮我看看,感激不尽!

**Comment by 404isNotFound** [comment]
我尝试将服务器上的ffmpeg版本升到4.1.3版本又出现了新的错误: `{
  id: '65ldabiutjwnn5z9',
  error: {
    type: 'error',
    error: Error: ffmpeg exited with code 1: Unrecognized option 'preset'.
    Error splitting the argument list: Option not found
    
        at ChildProcess.<anonymous> (/pv/ff/ffproject/node_modules/fluent-ffmpeg/lib/processor.js:182:22)
        at ChildProcess.emit (events.js:210:5)
        at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12),
    target: FFScene {
      _events: [Object],
      _eventsCount: 4,
      _maxListeners: undefined,
      conf: [Object],
      type: 'scene',
      parent: [FFCreator],
      id: 'scene1',
      children: [Array],
      filters: [Array],
      vLength: 1,
      hasInput: false,
      context: [FFContext],
      command: [FfmpegCommand],
      percent: 0,
      duration: 5,
      directory: '/pv/ff/ffproject/Template/cache/iv5e438fh74ruvm8',
      pathId: 'iv5e438fh74ruvm8',
      background: [FFBackGround],
      filepath: '/pv/ff/ffproject/Template/cache/iv5e438fh74ruvm8/scene1.mp4'
    }
  },
  eventName: 'single-error'
}`

**Comment by 404isNotFound** [comment]
尝试手动执行ffmpeg命令他出现了以下错误: 

[root@iZm5eeednvvtf4jpgv1rqlZ ffproject]# ffmpeg -i /pv/ff/ffproject/static/47/hj/1612513548853.mp4 -y -filter_complex color=c=#000000:d=5:size=576*1024[background1-0];[background1-0][0:v]overlay=x=0:y=0[video1-1];[video1-1]drawtext=bordercolor=#000000:borderw=3:fontcolor=#FFFC00:fontfile=/pv/ff/ffproject/static/font/klt.ttf:fontsize=60:text=般若诸佛:alpha='if(between(t,2,3),0+1*(t-2)/1,1)':x='if(between(t,2,3),168+0*(t-2)/1-0*pow((t-2)/1,2),168)':y='if(between(t,2,3),-30+200*(t-2)/1-100*pow((t-2)/1,2),70)':enable='between(t,2,99999)'[text1-1] -map [text1-1] -r 24 -t 5 -map 0 -hide_banner -map_metadata -1 -map_chapters -1 -c:v libx264 -profile:v main -preset medium -crf 20 -movflags faststart -pix_fmt yuv420p /pv/ff/ffproject/Template/cache/iv5e438fh74ruvm8/scene1.mp4
ffmpeg version 4.1.3 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-44)
  configuration: 
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/pv/ff/ffproject/static/47/hj/1612513548853.mp4':
  Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.49.100
  Duration: 00:00:09.86, start: 0.000000, bitrate: 1331 kb/s
    Stream #0:0(und): Video: h264 (High) (avc1 / 0x31637661), yuvj420p(pc), 1280x720, 1262 kb/s, 24 fps, 24 tbr, 12288 tbn, 48 tbc (default)
    Metadata:
      handler_name    : Core Media Video
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 16000 Hz, mono, fltp, 67 kb/s (default)
    Metadata:
      handler_name    : Core Media Audio
Filter color has an unconnected output
-bash: [background1-0][0:v]overlay=x=0:y=0[video1-1]: command not found
-bash: [video1-1]drawtext=bordercolor=#000000:borderw=3:fontcolor=#FFFC00:fontfile=/pv/ff/ffproject/static/font/klt.ttf:fontsize=60:text=般若诸佛:alpha=if(between(t,2,3),0+1*(t-2)/1,1):x=if(between(t,2,3),168+0*(t-2)/1-0*pow((t-2)/1,2),168):y=if(between(t,2,3),-30+200*(t-2)/1-100*pow((t-2)/1,2),70):enable=between(t,2,99999)[text1-1]: No such file or directory

**Comment by 404isNotFound** [comment]
@drawcall  请问你用的ffmpeg 是多少版本的

**Comment by 404isNotFound** [comment]
@drawcall    请问 你用的ffmpeg是多少版本的

**Comment by drawcall** [comment]
ffmpeg >= v4

**Comment by 404isNotFound** [comment]
谢谢
